import { mock_fotos_data } from "./fotos";

export const Albums = [
  {
    id: "congress-on-brain-2023",
    quantity: `${mock_fotos_data.length} imagens`,
    image: "/img-album/Cópia-de-Congress-On-Brain-2023-1.webp",
    title: "Congress On Brain 2023",
    subtitle: "Local, data e resumo do evento",
    photos: mock_fotos_data,
  },
  {
    id: "encontro-catarinense-2023",
    quantity: `${mock_fotos_data.length} imagens`,

    image: "/img-album/Cópia-de-Encontro_Catarinense_2023-3.webp",
    title: "Encontro Catarinense 2023",
    subtitle: "Local, data e resumo do evento",
    photos: mock_fotos_data,
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Dia_Nacional_Esquizofrenia_2023-1.webp",
    title: "Dia Nacional Esquizofrenia 2023",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Mandala-produção-oficina-artes-2021-1.webp",
    title: "Oficinas de Arte 2021",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "34 imagens",
    image: "/img-album/Cópia-de-Festa_15_anos_ABRE-2017-1.webp",
    title: "Festa de 15 anos ABRE 2017",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "4 imagens",
    image: "/img-album/Cópia-de-LIvro_Entre_Razão_Ilusão_2023-3.webp",
    title: "Congress On Brain 2023",
    subtitle: "Livro entre a Razão e a Ilusão",
    photos: [],
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Jorge-Assis-Palestra-sobre-esquizofrenia-2021-2.webp",
    title: "Encontros/Palestras",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "6 imagens",
    image: "/img-album/Cópia-de-Congress-On-Brain-2023-1.webp",
    title: "Congress On Brain 2023",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "5 imagens",
    image: "/img-album/Cópia-de-Encontro_Catarinense_2023-3.webp",
    title: "Encontro Catarinense 2023",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Dia_Nacional_Esquizofrenia_2023-1.webp",
    title: "Dia Nacional Esquizofrenia 2023",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Mandala-produção-oficina-artes-2021-1.webp",
    title: "Oficinas de Arte 2021",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "34 imagens",
    image: "/img-album/Cópia-de-Festa_15_anos_ABRE-2017-1.webp",
    title: "Festa de 15 anos ABRE 2017",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
  {
    quantity: "4 imagens",
    image: "/img-album/Cópia-de-LIvro_Entre_Razão_Ilusão_2023-3.webp",
    title: "Congress On Brain 2023",
    subtitle: "Livro entre a Razão e a Ilusão",
    photos: [],
  },
  {
    quantity: "3 imagens",
    image: "/img-album/Cópia-de-Jorge-Assis-Palestra-sobre-esquizofrenia-2021-2.webp",
    title: "Encontros/Palestras",
    subtitle: "Local, data e resumo do evento",
    photos: [],
  },
];
